version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      # Set Task Variables
      - TASK_FAMILY="hello-world-app"
      - CONTAINER_NAME="hello-world"
      - CLUSTER_NAME="hello-world-app"
      - SERVICE_NAME="hello-world-app-service"
      - EXECUTION_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/hello-world-app-ecsTaskExecutionRole"
      - TASK_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/hello-world-app-ecsTaskRole"

      # Write imagedefinitions.json (used later by CodePipeline)
      - echo "Writing imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

      # Register new ECS task definition using a heredoc
      - echo "Registering new ECS task definition (revision will auto-increment)..."
      - |
        # Use a shell heredoc (<<EOF) to safely contain the multi-line command and JSON
        aws ecs register-task-definition <<EOF
        --family ${TASK_FAMILY}
        --network-mode awsvpc
        --requires-compatibilities FARGATE
        --cpu "512"
        --memory "1024"
        --execution-role-arn ${EXECUTION_ROLE_ARN}
        --task-role-arn ${TASK_ROLE_ARN}
        --container-definitions '[
            {
              "name": "${CONTAINER_NAME}",
              "image": "${REPOSITORY_URI}:${IMAGE_TAG}",
              "portMappings": [{"containerPort": 8080, "protocol": "tcp"}],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/${TASK_FAMILY}",
                  "awslogs-region": "${AWS_DEFAULT_REGION}",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]'
        EOF

      # Force new deployment on ECS service
      - echo "Force new deployment on ECS service..."
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_FAMILY --force-new-deployment

      - echo "Deploy completed successfully!"
      - echo "New image running: $REPOSITORY_URI:$IMAGE_TAG"

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
